/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface FxCurrency {
  code: string;
  kind: string;
  scale: number;
}

export interface IamWorkspace {
  created_at: Generated<Timestamp>;
  id: string;
  name: string;
}

export interface LedgerJournalEntry {
  created_at: Generated<Timestamp>;
  entry_date: string;
  entry_type: string;
  id: string;
  memo: string | null;
  reverses_entry_id: string | null;
  sequence: Generated<Int8>;
  source_id: string;
  source_revision: number;
  source_type: string;
  workspace_id: string;
}

export interface LedgerLedgerAccount {
  archived_at: Timestamp | null;
  code: string;
  created_at: Generated<Timestamp>;
  currency: string;
  id: string;
  source_account_id: string | null;
  system_kind: string | null;
  type: string;
  workspace_id: string;
}

export interface LedgerPosting {
  account_type: string;
  amount: ColumnType<string, string, never>;
  created_at: Generated<Timestamp>;
  currency: string;
  entry_date: string;
  id: string;
  journal_entry_id: string;
  ledger_account_id: string;
  line_no: number;
  memo: string | null;
  split_id: string | null;
  workspace_id: string;
}

export interface DB {
  "fx.currency": FxCurrency;
  "iam.workspace": IamWorkspace;
  "ledger.journal_entry": LedgerJournalEntry;
  "ledger.ledger_account": LedgerLedgerAccount;
  "ledger.posting": LedgerPosting;
}
